{{ include "cora.serveralias" . }}
---
{{ include "cora.solr" . }}
---
{{ include "cora.idplogin" . }}
---
{{ include "cora.rabbitmq" . }}
---
{{ include "cora.fedora" . }}
---
{{ include "cora.fitnesse" . }}
---
{{ include "cora.gatekeeper" . }}
---
{{ include "cora.iip" . }}
---
{{ include "cora.jsclient" . }}
---
{{ include "cora.rest" . }}
---
{{ include "cora.postgresql" . }}
---
{{ include "cora.login" . }}
---
{{ include "cora.binaryconverter" . }}
---
{{ include "cora.apache" . }}
---
{{ include "cora.job-index" . }}
---
{{ include "cora.job-create-example-users" . }}
---
{{ include "cora.job-create-apptoken" . }}

