apiVersion: v2
name: systemone
description: A Helm chart for SystemOne on Kubernetes
type: application
version: 0.11.13
appVersion: 1.24.0
dependencies:
  - name: cora
    version: 3.3.0
    repository: file://../cora
