apiVersion: v2
name: systemone
description: A Helm chart for SystemOne on Kubernetes
type: application
version: 0.11.17
appVersion: 1.26.0
dependencies:
  - name: cora
    version: 3.5.0
    repository: file://../cora
