apiVersion: v2
name: systemone
description: A Helm chart for SystemOne on Kubernetes
type: application
version: 0.11.9
appVersion: 1.23.0
dependencies:
  - name: cora
    version: 3.2.0
    repository: file://../cora
