apiVersion: v2
name: systemone
description: A Helm chart for SystemOne on Kubernetes
type: application
version: 0.8.7
appVersion: 1.21.0
dependencies:
  - name: cora
    version: 1.9.0
    repository: file://../cora
