apiVersion: v2
name: systemone
description: A Helm chart for SystemOne on Kubernetes
type: application
version: 0.10.0
appVersion: 1.22.0
dependencies:
  - name: cora
    version: 3.1.0
    repository: file://../cora
