apiVersion: v2
name: alvin
description: A Helm chart for Alvin on Kubernetes
type: application
version: 0.6.10
appVersion: 0.0.1
dependencies:
  - name: cora
    version: 1.1.2
    repository: file://../cora
