apiVersion: v2
name: alvin
description: A Helm chart for Alvin on Kubernetes
type: application
version: 0.10.17
appVersion: 0.17.0
dependencies:
  - name: cora
    version: 3.5.0
    repository: file://../cora
