apiVersion: v2
name: alvin
description: A Helm chart for Alvin on Kubernetes
type: application
version: 0.7.14
appVersion: 0.12.0
dependencies:
  - name: cora
    version: 2.2.0
    repository: file://../cora
