apiVersion: v2
name: alvin
description: A Helm chart for Alvin on Kubernetes
type: application
version: 0.10.13
appVersion: 0.15.0
dependencies:
  - name: cora
    version: 3.3.0
    repository: file://../cora
