apiVersion: v2
name: alvin
description: A Helm chart for Alvin on Kubernetes
type: application
version: 0.9.1
appVersion: 0.13.0
dependencies:
  - name: cora
    version: 3.1.0
    repository: file://../cora
