apiVersion: v2
name: alvin
description: A Helm chart for Alvin on Kubernetes
type: application
version: 0.7.2
appVersion: 0.0.1
dependencies:
  - name: cora
    version: 1.8.0
    repository: file://../cora
