apiVersion: v2
name: alvin
description: A Helm chart for Alvin on Kubernetes
type: application
version: 0.6.45
appVersion: 0.0.1
dependencies:
  - name: cora
    version: 1.3.1
    repository: file://../cora
