apiVersion: v2
name: alvin
description: A Helm chart for Alvin on Kubernetes
type: application
version: 0.8.0
appVersion: 0.12.0
dependencies:
  - name: cora
    version: 3.0.0
    repository: file://../cora
