apiVersion: v2
name: alvin
description: A Helm chart for Alvin on Kubernetes
type: application
version: 0.10.1
appVersion: 0.14.0
dependencies:
  - name: cora
    version: 3.2.0
    repository: file://../cora
