apiVersion: v2
name: diva
description: A Helm chart for DiVA on Kubernetes
type: application
version: 0.7.34
appVersion: 1.14.0
dependencies:
  - name: cora
    version: 3.0.0
    repository: file://../cora
