apiVersion: v2
name: diva
description: A Helm chart for DiVA on Kubernetes
type: application
version: 0.10.14
appVersion: 1.16.0
dependencies:
  - name: cora
    version: 3.2.0
    repository: file://../cora
