apiVersion: v2
name: diva
description: A Helm chart for DiVA on Kubernetes
type: application
version: 0.6.83
appVersion: 0.0.1
dependencies:
  - name: cora
    version: 1.3.1
    repository: file://../cora
