apiVersion: v2
name: diva
description: A Helm chart for DiVA on Kubernetes
type: application
version: 0.9.1
appVersion: 1.15.0
dependencies:
  - name: cora
    version: 3.2.0
    repository: file://../cora
