apiVersion: v2
name: diva
description: A Helm chart for DiVA on Kubernetes
type: application
version: 0.6.32
appVersion: 0.0.1
dependencies:
  - name: cora
    version: 1.2.0
    repository: file://../cora
