apiVersion: v2
name: diva
description: A Helm chart for DiVA on Kubernetes
type: application
version: 0.10.59
appVersion: 1.19.0
dependencies:
  - name: cora
    version: 3.5.0
    repository: file://../cora
