apiVersion: v2
name: diva
description: A Helm chart for DiVA on Kubernetes
type: application
version: 0.7.5
appVersion: 0.0.1
dependencies:
  - name: cora
    version: 1.8.0
    repository: file://../cora
