apiVersion: v2
name: diva
description: A Helm chart for DiVA on Kubernetes
type: application
version: 0.7.32
appVersion: 1.14.0
dependencies:
  - name: cora
    version: 2.3.0
    repository: file://../cora
