apiVersion: v2
name: diva
description: A Helm chart for DiVA on Kubernetes
type: application
version: 0.10.33
appVersion: 1.17.0
dependencies:
  - name: cora
    version: 3.3.0
    repository: file://../cora
