deploy:
  fitnesse: true

data:
  dataDividers: "cora jsClient alvin alvinPreview alvinTestSystem alvinProduction alvinData"

externalAccess:
  systemUrl: http://192.168.49.2:30981
  deploymentName: Alvin - lokalt (ðŸ‘€ k8s)
  loginRestUrl: http://172.18.0.15:31981/login/rest/
django:
  allowedHosts: "*"
shibboleth:
  domain: local
