deploy:
  fitnesse: true

data:
  dataDividers: "cora jsClient alvin alvinPreview alvinTestSystem alvinProduction alvinData"
  exampleUsers: 
    - "141414"
    - "151515"
    - "coraUser:4412566252284358"
    
externalAccess:
  systemUrl: http://192.168.49.2:30981
  systemRestUrl: http://192.168.49.2:30981/rest/
  deploymentName: Alvin - lokalt (ðŸ‘€ k8s)
  loginRestUrl: http://192.168.49.2:30981/login/rest/
django:
  allowedHosts: "*"
shibboleth:
  domain: local
