deploy:
  fitnesse: true
  playwright: true

data:
  dataDividers: "cora jsClient diva divaPreview divaPre divaProduction divaClient"

externalAccess:
  systemUrl: http://192.168.49.2:30982
  deploymentName: DiVA - lokalt (ðŸ‘€ k8s)
  loginRestUrl: http://172.18.0.15:31982/login/rest/
shibboleth:
  domain: local

security:
  divaClientSecureSessionCookie: false
  divaClientAppTokenUsers: [{"displayName":"Diva Admin","loginId":"divaAdmin@cora.epc.ub.uu.se","appToken":"49ce00fb-68b5-4089-a5f7-1c225d3cf156"}]
