apiVersion: v1
kind: Secret
metadata:
  name: systemone-secret
type: Opaque
data:
  POSTGRES_USER: c3lzdGVtb25l
  POSTGRES_PASSWORD: c3lzdGVtb25l
  binaryConverterLoginId: c3lzdGVtb25lQWRtaW5Ac3lzdGVtLmNvcmEudXUuc2U=
  binaryConverterAppToken: NWQzZjNlZDQtNDkzMS00OTI0LTlmYWEtOGVhZjVhYzY0NTdl
  indexLoginId: c3lzdGVtb25lQWRtaW5Ac3lzdGVtLmNvcmEudXUuc2U=
  listSequenceLoginId: c3lzdGVtb25lQWRtaW5Ac3lzdGVtLmNvcmEudXUuc2U=

#echo -n 'Hello, World!' | base64
