deploy:
  fitnesse: true

data:
  dataDividers: "cora jsClient systemOne testSystem"

externalAccess:
  systemUrl: http://192.168.49.2:30980
  deploymentName: SystemOne - lokalt (ðŸ‘€ k8s)
  loginRestUrl: http://172.18.0.15:31980/login/rest/
shibboleth:
  domain: local