deploy:
  fitnesse: true

data:
  dataDividers: "cora jsClient systemOne testSystem"
  exampleUsers: 
    - "141414"
  
externalAccess:
  systemUrl: http://192.168.49.2:30980
  systemRestUrl: http://192.168.49.2:30980/rest/
  deploymentName: SystemOne - utveckling k8s ðŸ‘€
  loginRestUrl: http://192.168.49.2:30980/login/rest/
shibboleth:
  domain: local