deploy:
  fitnesse: true

data:
  dataDividers: "cora jsClient systemOne testSystem"

externalAccess:
  systemUrl: http://192.168.49.2:30980
  deploymentName: "SystemOne - lokalt (â˜¸ k8s)"
  loginRestUrl: http://192.168.49.2:31980/login/rest/
shibboleth:
  domain: local